name: Deploy Nodejs app to ec2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run Containers
        run: |
          cd /home/ec2-user/node-action-workflow
          git pull origin main
          docker-compose up -d --build

      # - name: Deploy by ssh
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ec2-user
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd /home/ec2-user/node-action-workflow
      #       git pull origin main
      #       docker-compose up -d --build
